# используем образы из собственого реестра, volume не подключаем так как все файлы находяться в образе (через COPY)
version: "3.7"
services:
  gateway:
    image: ${REGISTRY}/micro-gateway:${IMAGE_TAG}
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - api

  frontend:
    image: ${REGISTRY}/micro-frontend:${IMAGE_TAG}
    restart: always

  api:
    image: ${REGISTRY}/micro-api:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/micro-api-php-fpm:${IMAGE_TAG}
    restart: always