version: "3.7"
services:
  gateway:
    build:
      context: gateway/docker
      dockerfile: dev/nginx/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend/docker/dev/nginx
    volumes:
      - ./frontend:/app

  api:
    build:
      context: api/docker
      dockerfile: dev/nginx/Dockerfile
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker
      dockerfile: dev/php-fpm/Dockerfile
    container_name: php-fpm
    volumes:
      - ./api:/app
      - ./api/docker/dev/php/.bashrc:/root/.bashrc
      - ./api/docker/dev/php/.bash_aliases:/root/.bash_aliases
    environment:
      APP_ENV: 'dev'
      APP_DEBUG: 1

  api-php-cli:
    build:
      context: api/docker
      dockerfile: dev/php-cli/Dockerfile
    container_name: php-cli
    volumes:
      - ./api:/app
      - ./api/docker/dev/php/.bashrc:/root/.bashrc
      - ./api/docker/dev/php/.bash_aliases:/root/.bash_aliases
    environment:
      APP_ENV: 'dev'
      APP_DEBUG: 1