version: "3.7"
services:
  gateway:
    build:
      context: gateway/docker/dev/nginx
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - frontend
      - api

  frontend:
    build:
      context: frontend/docker/dev/nginx
    volumes:
      - ./frontend:/app

  api:
    build:
      context: api/docker/dev/nginx
    volumes:
      - ./api:/app
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker/dev/php-fpm
    volumes:
      - ./api:/app
    environment:
      APP_DEBUG: 1

  api-php-cli:
      build:
        context: api/docker/dev/php-cli
      volumes:
        - ./api:/app