# используем образы из собственого реестра, volume не подключаем так как все файлы находяться в образе (через COPY)
version: "3.7"
services:
  gateway:
    image: ${REGISTRY}/micro-gateway:${IMAGE_TAG}
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - api

  frontend:
    image: ${REGISTRY}/micro-frontend:${IMAGE_TAG}
    restart: always

  api:
    image: ${REGISTRY}/micro-api:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/micro-api-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_ENV: 'prod'
      APP_DEBUG: 0
      DB_HOST: api-postgres
      DB_USER: cubic
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: micro

  api-php-cli:
    image: ${REGISTRY}/micro-api-php-cli:${IMAGE_TAG}
    environment:
      APP_ENV: 'prod'
      APP_DEBUG: 0
      DB_HOST: api-postgres
      DB_USER: cubic
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: micro

  api-postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: cubic
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: micro
    volumes:
      - api-postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  api-postgres: