# устанавливаем certbot
# @see https://www.digitalocean.com/community/tutorials/how-to-secure-apache-with-let-s-encrypt-on-debian-10
---
-   name: Update apt packages
    apt:
        update_cache: yes

-   name: Add Certbot repository
    apt_repository:
        repo: 'deb http://ftp.debian.org/debian buster-backports main'
        state: present
        filename: buster-bacports
        update_cache: yes

-   name: Install Certbot
    apt:
        name: certbot
        state: present
        default_release: buster-backports
        update_cache: yes

-   name: Copy Certbot configuration
    copy:
        src: files/cli.ini
        dest: /etc/letsencrypt/cli.ini
        owner: root
        group: root
        mode: 0644
# удаляем старые пакеты и зависимости
-   name: Remove useless package
    apt:
        autoclean: yes

-   name: Remove useless dependencies
    apt:
        autoremove: yes