# настройки для подключения к серверам (в секции server можно указывать несколько серверов)
all:
    children:
        site:
            hosts:
                server:
                    ansible_connection: ssh
                    ansible_user: root
                    ansible_host: 5.53.125.128
                    ansible_port: 22
                    # указываем путь к интерпретатору python на удаленом сервере
                    #ansible_python_interpreter: /usr/bin/python3