# настройки для подключения к серверам (в секции server можно указывать несколько серверов)
all:
    children:
        site:
            hosts:
                server:
                    ansible_connection: ssh
                    ansible_user: ubuntu
                    ansible_host: 3.120.128.1
                    ansible_port: 22
                    # указываем путь к интерпретатору python на удаленом сервере
                    ansible_python_interpreter: /usr/bin/python3